<?php $title = $hero->getName() ?>
<?php $itemAll = '../' ?>
<?php $itemAddNew = '../new' ?>
<?php $itemSearch = '../search' ?>
<?php $style = '../css/style.css' ?>
<?php include('layouts/head.php') ?>
<body>
<?php include('layouts/navbar.php') ?>

<div class="container">
    <center>
        <p class="heada">
            <?= $hero->getId() ?>:
            <?= $hero->getName() ?>
        </p>

        <div class="row">
            <div style="margin: 0 auto; ">
                <table class="table table-bordered table-striped table-hover top-space">
                    <tr>
                        <th>Role</th>
                        <th>Abilities</th>
                        <th>Difficulty</th>
                    </tr>
                    <tr>
                        <td><?= $hero->getRole() ?></td>
                        <td><?= $hero->getAbilities() ?></td>
                        <td><?= $hero->getDifficulty() ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </center>
</div>
</body>
</html>