<?php $title = 'Search' ?>
<?php $itemAll = '../' ?>
<?php $itemAddNew = '../new' ?>
<?php $itemSearch = '../search' ?>
<?php $style = 'css/style.css' ?>
<?php $style2 = '../css/style.css' ?>
<?php include('layouts/head.php') ?>
<body>
<?php include('layouts/navbar.php') ?>

<div class="container top-space">
    <center>
        <p class="heada">Search</p>
        <form class="pure-form" action="/search" method="POST">
            <label for="heroSearch">
                Search for
            </label>
            <input class="top-space" name="search" id="heroSearch" type="text"><br/>

            <input type="submit" class="pure-button" value="Search"/>
        </form>


        <?php if (count($heroes) > 0): ?>
            <table class="table table-bordered table-hover table-striped">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Role</th>
                    <th>Abilities</th>
                    <th>Difficulty</th>
                    <th>Actions</th>
                </tr>
                <?php foreach ($heroes as $hero): ?>

                    <tr>
                        <td><?= $hero->getId() ?></td>
                        <td><?= $hero->getName() ?></td>
                        <td><?= $hero->getRole() ?></td>
                        <td><?= $hero->getAbilities() ?></td>
                        <td><?= $hero->getDifficulty() ?></td>
                        <td>
                            <a href="<?= $router->pathFor('hero-detail', ['hero_id' => $hero->getId()]) ?>">
                                view
                            </a>
                            <span> | </span>
                            <a href="<?= $router->pathFor('hero-delete', ['hero_id' => $hero->getId()]) ?>">
                                remove
                            </a>
                            <span> | </span>
                            <a href="<?= $router->pathFor('hero-edit', ['hero_id' => $hero->getId()]) ?>">
                                edit
                            </a>
                        </td>
                    </tr>

                <?php endforeach ?>
            </table>
        <?php else: ?>
            <p class="heada">
                No results!
            </p>
        <?php endif ?>
    </center>
</div>
</body>
</html>